# Generated by Django 6.0 on 2025-12-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default='Draft', max_length=20),
        ),
    ]
