# Generated by Django 6.0 on 2026-01-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_sociallinks_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'SocialLinks'},
        ),
    ]
